name: S3 Sample
on:
  push:
    branches:
      - main

jobs:
  update-s3:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Update S3
        env: 
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 cp ./README.md s3://$S3_BUCKET/ --quiet